name: Test

on:

  push:
  pull_request:


jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: Test dry run
      run: |
        timeout 5s bun run start || if [ $? -eq 124 ]; then exit 0; else exit 1; fi

  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: Test Compile
      run: bun run build